version: 2.1
jobs:
   configure_infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["f3:15:94:7f:a2:39:bd:f0:06:0b:43:fe:eb:f2:ab:18"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory playbook.yml



#  get_IP:
#    docker:
#      - image: amazon/aws-cli
#    steps:
#      - checkout
#      - run:
#         name: EC2 IP Addr 
#         command: |
#           aws ec2 describe-instances \
#                         --filters "Name=key-name,Values=udacityDOkeypair" \
#                         --query 'Reservations[*].Instances[*].PublicIpAddress' \
#                         --output text  --region us-west-2
#
#           aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text --region us-west-2

workflows:
  my_workflow:
    jobs:
      - configure_infra
#      - get_IP

